"""initial schema

Revision ID: 083f9b12445b
Revises: 
Create Date: 2026-09-04 23:14:25.145234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '083f9b12445b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('employee_number', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('train_id', sa.String(), nullable=False),
    sa.Column('original_train_id', sa.String(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('origin_station', sa.String(), nullable=True),
    sa.Column('final_station', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('on_duty', sa.DateTime(), nullable=True),
    sa.Column('initial_os', sa.DateTime(), nullable=True),
    sa.Column('final_os', sa.DateTime(), nullable=True),
    sa.Column('off_duty', sa.DateTime(), nullable=True),
    sa.Column('run_miles', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('train_length', sa.Integer(), nullable=True),
    sa.Column('cars', sa.SmallInteger(), nullable=True),
    sa.Column('axles', sa.String(), nullable=True),
    sa.Column('lead_unit', sa.String(), nullable=True),
    sa.Column('trailing_units', sa.String(), nullable=True),
    sa.Column('dp_units', sa.String(), nullable=True),
    sa.Column('release_care_control', sa.DateTime(), nullable=True),
    sa.Column('rx_rtc', sa.String(), nullable=True),
    sa.Column('rx_mile_point', sa.String(), nullable=True),
    sa.Column('rx_time', sa.DateTime(), nullable=True),
    sa.Column('rest', sa.Integer(), nullable=True),
    sa.Column('work_minutes', sa.Integer(), sa.Computed('CAST(EXTRACT(EPOCH FROM (off_duty - on_duty)) / 60 AS INTEGER)', persisted=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'pending_confirmation', 'confirmed', 'disputed', 'expired', name='job_status'), nullable=False),
    sa.Column('source', sa.Enum('app_entry', 'historic_import', name='job_source'), nullable=False),
    sa.Column('last_edited_by', sa.String(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_edited_by'], ['users.employee_number'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('job_edits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('edited_by', sa.String(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('change', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.employee_number'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('employee_number', sa.String(), nullable=False),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['employee_number'], ['users.employee_number'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'employee_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_table('job_edits')
    op.drop_table('jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
